import { useState, useEffect } from "react";
import Head from "next/head";
import Nav from "../components/Nav";
import Images from "../components/Images";
import Footer from "../components/Footer";
import client from "../client";

export default function Home() {
  const [settings, setSettings] = useState<any>({});
  useEffect(() => {
    client
      .fetch(`*[_type == "settings"][0]{..., landingBackground{asset->{url}}}`)
      .then((settings: any) => {
        console.log("settings:", settings);
        setSettings(settings);
      });
  }, []);
  return (
    <>
      <Head>
        <title>
          {settings?.siteName ? settings.siteName : "Humboldt Life"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          backgroundColor: "#F3F4F6",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Nav
          siteName={settings?.siteName ? settings.siteName : "Humboldt Life"}
        />
        <div
          style={{
            width: "100%",
            backgroundColor: "#EEF0F2",
            height: "95vh",
            margin: "10vh 0 0 0",
            backgroundImage: 'URL("/images/landing_section_bg.png")',
            backgroundSize: "cover",
          }}
        >
          <section className="mt-8 absolute ml-16">
            <h1 className="text-7xl" style={{ color: "#1A1F16" }}>
              {settings?.landingTitle
                ? settings.landingTitle
                : "Life at Humboldt"}
            </h1>
            <p style={{ color: "#1A1F16" }}>
              {settings?.landingSubtitle
                ? settings.landingSubtitle
                : "A photo album site to document my time there"}
            </p>
          </section>
        </div>
        <Images />
        <Footer />
      </main>
    </>
  );
}
